### ISSUE TITLE
Getting listed on modelica.org/libraries

### ISSUE THREAD

**Issue by dietmarw** [open-ideas/FastBuildings#6]
I was wondering if you would be interested to get listed on https://modelica.org/libraries

Just let me know and I can fork your repo it get's listed.

**Comment by saroele** [comment]
Hi Dietmar,
We wondered how it works to get listed there :-)  The FastBuildings library is listed, but I don't remember how that happened.  The IDEAS library however would be nice to get on that list.  It's available here: https://github.com/open-ideas/IDEAS

So you just fork it to some Modelica organization website and it get's listed from there?  Cool :-)

**Comment by dietmarw** [comment]
Hi,
well all it takes is a simple message to the webmaster (as it is written on modelica.org/libraries ;-)) and yes technically we generate the listing each night with a python script that grabs all projects that are listed under https://github.com/[modelica|modelica-3rdparty|modelica-deprecated]. 

If you want to have downloads available directly then you need to tag your repo. We recommend to first create a release branch, possibly rearrange the file structure (e.g., `PackageName 1.2`) and then tag that one. That way people downloading the tagged zips get the correct folder hierarchy. 

I forgotten that I've already forked FastBuildings, but will do this for IDEAS. But you should create a tag for it soon, otherwise it looks like there is no release and only the development version is available (might be just as well, I'll leave that up to you).

**Comment by saroele** [comment]
Thanks, we'll start using tags then! I'll communicate with the IDEAS maintainers.

**Comment by dietmarw** [comment]
I should probably close this one since FastBuildings already was listed and IDEAS is now.

**Comment by saroele** [comment]
Perfect! Thanks and see you probably at the modelica conf!

**Comment by dietmarw** [comment]
We are actually planning a tutorial session on the usage of git and github especially for library developers and how all this is integrated in our website and [impact](https://github.com/xogeny/impact) infrastructure. Might be interesting to you.

**Comment by rubenbaetens** [comment]
Hi @dietmarw, we've tagged an official release in the https://github.com/open-ideas/IDEAS repository, so we were wondering if this could be mentioned on https://modelica.org/libraries ?

**Comment by dietmarw** [comment]
for some reason my syncing script did not fetch the tags. Thanks for the heads-up. It's already on [http://impact.github.io](http://impact.github.io/#/library /07423837d9dc21b57eb9137a5c42d2a13ae87a81) now and will be on modelica.org/libraries probably tomorrow.

**Comment by rubenbaetens** [comment]
Hm, it seems you fetched a very old tag on modelica.org/libraries, while we made a new realese `v0.3.0`.

**Comment by dietmarw** [comment]
Tags are sorted by name not date. So `
versionLinearisationPaper` > `v0.3.0` Nothing much I can do about. I suggest you rename the paper tag to something starting with <`v...`

**Comment by rubenbaetens** [comment]
OK, thx.
